<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-05T19:42:13 IST" name="Suite" finished-at="2025-02-05T19:42:22 IST" duration-ms="8164">
    <groups>
    </groups>
    <test started-at="2025-02-05T19:42:13 IST" name="Test" finished-at="2025-02-05T19:42:22 IST" duration-ms="8164">
      <class name="testcases.Loginpage_TC">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:testcases.Loginpage_TC@7188af83]" started-at="2025-02-05T19:42:14 IST" name="beforeMethod" finished-at="2025-02-05T19:42:18 IST" duration-ms="3782" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="perform_loginFor_QAaccount_allAccess()[pri:0, instance:testcases.Loginpage_TC@7188af83]" started-at="2025-02-05T19:42:18 IST" name="perform_loginFor_QAaccount_allAccess" finished-at="2025-02-05T19:42:21 IST" duration-ms="3412" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- perform_loginFor_QAaccount_allAccess -->
        <test-method signature="Validate_dashboardURL_afterLogin()[pri:0, instance:testcases.Loginpage_TC@7188af83]" started-at="2025-02-05T19:42:21 IST" name="Validate_dashboardURL_afterLogin" finished-at="2025-02-05T19:42:21 IST" duration-ms="132" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Dashboard URL does not match! expected [https://ytr.insemitech.com///dashboard/home/] but found [https://ytr.insemitech.com/dashboard/home/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Dashboard URL does not match! expected [https://ytr.insemitech.com///dashboard/home/] but found [https://ytr.insemitech.com/dashboard/home/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases.Loginpage_TC.Validate_dashboardURL_afterLogin(Loginpage_TC.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Validate_dashboardURL_afterLogin -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:testcases.Loginpage_TC@7188af83]" started-at="2025-02-05T19:42:21 IST" name="afterMethod" finished-at="2025-02-05T19:42:22 IST" duration-ms="381" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Validate_dashboardURL_afterLogin status=FAILURE method=Loginpage_TC.Validate_dashboardURL_afterLogin()[pri:0, instance:testcases.Loginpage_TC@7188af83] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testcases.Loginpage_TC -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
